# QA pipeline at SonarSource
# Based on https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin

RUN_ACTIVITY:
  - run-db-unit-tests-mssql2016
  - run-db-integration-tests-mssql2016-Category1
  - run-db-integration-tests-mssql2016-Category2
  - run-db-integration-tests-mssql2016-Category3
  - run-db-integration-tests-mssql2016-Category4
  - run-db-integration-tests-mssql2016-Category5
  - run-db-integration-tests-mssql2016-Category6
  - run-upgrade-tests-mssql2016

exclude:
  - RUN_ACTIVITY: run-db-unit-tests-mssql2016
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2016-Category1
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2016-Category2
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2016-Category3
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2016-Category4
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2016-Category5
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2016-Category6
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-upgrade-tests-mssql2016
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-mssql2016
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2016-Category1
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2016-Category2
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2016-Category3
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2016-Category4
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2016-Category5
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2016-Category6
    SLAVE_TYPE: windows 
  - RUN_ACTIVITY: run-upgrade-tests-mssql2016
    SLAVE_TYPE: windows
  